### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by NathanTech7713** [jsvine/pdfplumber#507] opened 2021-09-21 01:47 UTC
Hi there,

So this is a question rather than a bug report or anything like that, so I hope it's okay to put it here.
I noticed in the documentation of the library (which is super great by the way) that filling in form data is not supported?
That is to say from what I am reading, the library can retrieve the form fields, but can not save if the user, for instance, fills in the a text box?
Have I understood this correctly?

If I wanted that functionality, but everything else about this library fits, do yu have any recommendations for something that could compliment the library to do that?

As an aside question, is there a PDF standard that notes one font size being classed as a heading, while anything below that size is classed as just big text *I suppose there's no difference visually) but I was approaching this from an accessibility point of view for blind folk.
Related to my last question, in the docs it mentions attributes on words that show left positioning from page. I presume this could be used to work out, for instance, if something was centered. What unit is this using?

I'm sorry if these questions are really obvious and kind of dumb, but hopefully someone will find the time to point me in the right direction :)

**Comment by jsvine** [comment] 2021-09-21 02:08
Hi, there. No need to apologize. Responses below:

> That is to say from what I am reading, the library can retrieve the form fields, but can not save if the user, for instance, fills in the a text box?

Correct. This library is focused only on parsing PDFs; it is not a tool for writing/creating them.

> If I wanted that functionality, but everything else about this library fits, do yu have any recommendations for something that could compliment the library to do that?

I haven't used PDF-creation tools much, but `pdfrw` may fit your needs (though appears to no longer be maintained): https://github.com/pmaupin/pdfrw

> What unit is this using?

These are "points"; and, according to the PDF spec, the standard unit is 72 points/inch: https://www.pdfscripting.com/public/PDF-Page-Coordinates.cfm

Closing for now, since this is not a bug report or feature request, but feel free to continue the discussion.

**Closed as completed by jsvine** 2021-09-21 02:08 UTC
