### ISSUE TITLE
Handling curved characters and extracting words for curved characters

### ISSUE THREAD

**Issue by sreeni5493** [jsvine/pdfplumber#404] opened 2021-04-05 08:31 UTC
[Artwork_bavaria.pdf](https://github.com/jsvine/pdfplumber/files/6257128/Artwork_bavaria.pdf)
For this example: There are curved text. The curved text have the upright flag as "True". Also when extracting words using extract_words, they split into characters or half broken words. Anyway this could be solved?

**Comment by samkit-jain** [comment] 2021-04-06 16:38
Possibly a duplicate of #400

**Comment by jsvine** [comment] 2021-04-08 03:28
Very interesting example PDF, thank you for sharing. Outside of the fact that `pdfminer.six` has a very narrow definition of "upright" — see prior discussion [here](https://github.com/jsvine/pdfplumber/issues/368#issuecomment-798808061) — I don't see a bug here. But — per that same discussion — I do think it's worth trying to get `pdfminer.six` to expose each character's `matrix` property, which would let you identify arbitrarily rotated characters and handle them with your own logic:

> Of course, as you note, someone might be interested to know _the precise_ rotation, rather than just the binary `upright` value. For that, `pdfplumber` could expose the `matrix` property, which it currently does not — but I'll add this to my to-do list. From that, you could calculate the rotation (or perhaps `pdfplumber` could provide a utility function to do the same).

(Handling arbitrarily-rotated characters is, however, I think outside the scope of `extract_words(...)`. I cannot think of a widely-applicable heuristic that one could apply to situations like these.)

Closing for now, but feel free to continue the discussion.

**Closed as completed by jsvine** 2021-04-08 03:28 UTC
