### ISSUE TITLE
Extract paragraphs

### ISSUE THREAD

**Issue by janandreschweiger** [jsvine/pdfplumber#331] opened 2021-01-05 21:22 UTC
Hey everyone,
my firm plans on using your great framework for our search engine. It is necessary for us to split large pdf-files into smaller paragraphs.

Unfortunately, when reading a pdf file like this http://kib.kiev.ua/x86docs/Intel/5LP/335252-001.pdf the paragraphs are separated by only one line break. It would be great if there is an option for detecting paragraphs (or large spaces in the text), without manually calculating the boundaries.

We are thankful for any help!

**Comment by samkit-jain** [comment] 2021-01-06 08:45
Hi @janandreschweiger Appreciate your interest in the library. Unfortunately, this is something not supported out-of-the-box but we plan on having this feature integrated in pdfplumber. I am closing this issue since it is a duplicate of #10 and #295 .

If you don't want to manually calculate the boundaries, may I suggest you to try [pdftotext](https://www.xpdfreader.com/pdftotext-man.html) instead? For example, to get the text from page 7, run `pdftotext -f 7 -l 7 -layout input.pdf output.txt` which will give you the output as 
```
                The processor performs IA-32e paging by traversing a 4-level hierarchy of paging
                structures whose root structure resides at the physical address in control register
                CR3. Each paging structure is 4-KBytes in size and comprises 512 8-byte entries. The
                processor uses the upper 36 bits of a linear address (bits 47:12), 9 bits at a time, to
                select paging-structure entries from the hierarchy.

Note:           Figure 1-1 illustrates the translation of a linear address to a 4-KByte page. The paging
                process can be configured so that the translation of some linear addresses stops one or
                two levels earlier, translating instead to 2-MByte pages or 1-GByte pages.

                In general, bits 51:12 of each paging-structure entry contain a 4-KByte aligned
                physical address. For each entry except the last, this address is that of the next paging
                structure; in the last entry, it is the physical address of a 4-KByte page frame. The
                final physical address is obtained by combining this page-frame address with the page
                offset, bits 11:0 of the original linear address.

                Because only bits 47:0 of a linear address are used in address-translation, the
                processor reserves bits 63:48 for future expansion using a concept known as
                canonicality. A linear address is canonical if bits 63:47 of the address are identical.
                (Put differently, a linear address is canonical only if bits 63:48 are a sign-extension of
                bit 47, which is the uppermost bit used in linear-address translation.)

                When a 64-bit linear address is generated to access memory, the processor first
                confirms that the address is canonical. If the address is not canonical, the memory
                access causes a fault, and the processor makes no attempt to translate the address.1

                Intel 64 architecture includes numerous registers that are defined to hold linear
                addresses. These registers may be loaded using a variety of instructions. In most
                cases, these instructions cause a general-protection exception (#GP) if an attempt is
                made to load one of these registers with a value that is not canonical.

                Physical-address bits in a paging-structure entry beyond the enumerated physical-
                address width are reserved. A page-fault exception (#PF) results if an attempt is made
                to access a linear address whose translation encounters a paging-structure entry that
                sets any of those bits.


1.2             Linear-Address Width and VMX Transitions
                VM entries and VM exits manipulate numerous processor registers that contain linear
                addresses. The transitions respect the processor’s linear-address width in a manner
                based on canonicality.

                Certain fields in the VMCS correspond to registers that contain linear addresses.
                VM entries confirm that most of those fields contain values that are canonical. Some
                registers, such as RIP and the LDTR base address, receive special treatment.

                VM exits save into the VMCS the state of certain registers, some of which contain linear
                addresses. Because the processor generally ensures that the values in these registers
                are canonical (see Section 1.1), the values that VM exits save for these registers will
                generally be canonical.




 1. In general, an attempt to access memory using a linear address that is not canonical causes a
    general-protection exception (#GP). A stack-fault exception — #SS — occurs instead if the
    memory access was made using the SS segment.


Document Number: 335252-001, Revision: 1.0                                                                   5
```

**Closed as completed by samkit-jain** 2021-01-06 08:45 UTC
Labels: troubleshooting
