### ISSUE TITLE
TypeError: PageImage.debug_tablefinder() got an unexpected keyword argument 'table_settings'

### ISSUE THREAD

**Issue by n-traore** [jsvine/pdfplumber#1237] opened 2024-12-19 22:59 UTC
## Describe the bug
I am trying to debug a table extraction as shown in the docs ([here](https://github.com/jsvine/pdfplumber/tree/stable?tab=readme-ov-file#visually-debugging-the-table-finder)), and I am getting a type error on the `debug_tablefinder()` method: 

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[16], line 1
----> 1 img.debug_tablefinder(table_settings={})

TypeError: PageImage.debug_tablefinder() got an unexpected keyword argument 'table_settings'
```

## Code to reproduce the problem
```python
import pdfplumber

pdf = pdfplumber.open("report.pdf")
page2 = pdf.pages[1]
img = page2.to_image()
img.debug_tablefinder(table_settings={})
```

## PDF file

Not relevant, the issue is the same with any pdf file.

## Expected behavior

The method should work and return an image

## Actual behavior

An error is thrown.

## Screenshots

![image](https://github.com/user-attachments/assets/edab6150-9783-4560-bee0-44dbdfd82c57)

## Environment

- pdfplumber version: [0.11.4 and 0.11.3]
- Python version: [3.10.11]
- OS: [Windows]

**Comment by n-traore** [comment] 2024-12-19 23:06
Closing this as it appears to work with passing the dictionary only (without keyword `table_settings`), but this should be reflected in the docs, especially since the keyword argument works for `page.debug_tablefinder()`. This is confusing.

**Comment by cmdlineluser** [comment] 2024-12-20 11:40
You should probably keep the issue is open so that it can get fixed.

It seems the kwarg for `debug_tablefinder` is `tf=` for some reason.

**Comment by jsvine** [comment] 2024-12-31 14:48
Thank you @n-traore and @cmdlineluser — now fixed in commit above and on `develop`.

**Closed as completed by jsvine** 2024-12-31 14:48 UTC
Labels: bug
