### ISSUE TITLE
is it capable to extract no-explicit-line table?

### ISSUE THREAD

**Issue by sidaliu1014** [jsvine/pdfplumber#358] opened 2021-02-22 06:28 UTC
Hello team,

I am trying to extract table, which doesnt have vertical line or horizontal line from attached pdf.

I tried table_settings = {
         "vertical_strategy": "text",
         "horizontal_strategy": "text",
     } but result wasn't good. could you kindly advise if any way to extract no-explicit-line table (highlighted in yellow)? thanks.
[p4 (3).pdf](https://github.com/jsvine/pdfplumber/files/6019891/p4.3.pdf)

**Comment by jsvine** [comment] 2021-02-23 14:08
Hello. I can think of two possible approaches you could try:

- Setting `explicit_horizontal_lines` and `explicit_vertical_lines` ([documentation here](https://github.com/jsvine/pdfplumber/#table-extraction-settings)), either hardcoded or based on calculations you devise.
- Using `page.crop(...)` to select only the table area, and then using your original `table_settings`.


You could also try another table-extraction program, such as [Camelot](https://camelot-py.readthedocs.io/en/master/).

Closing this issue for now, since it is not a bug or feature request, but feel free to continue the discussion.

**Closed as completed by jsvine** 2021-02-23 14:08 UTC
