### ISSUE TITLE
Text extraction generated words have location that is completely off from where they actually are present

### ISSUE THREAD

**Issue by sreeni5493** [jsvine/pdfplumber#425] opened 2021-05-03 09:07 UTC
[v2.pdf](https://github.com/jsvine/pdfplumber/files/6413875/v2.pdf)

In this case, the PDF word locations are completely off. 

Please refer to below image generated from the following code:
```
import pdfplumber

pdf_path = './v2.pdf'

pdf = pdfplumber.open(pdf_path)

page=pdf.pages[0]

im = page.to_image(resolution=150)

im.draw_rects(page.extract_words(use_text_flow=True))

im.save('./asd.png')
```

The words are not properly marked. This is leading to highlighting issue. Anyway this can be fixed from our end itself or is this a more fundamental issue?

![asd](https://user-images.githubusercontent.com/15212113/116858957-db1b6700-ac1c-11eb-9779-3d75c466d1da.png)

Thanks.

**Comment by sreeni5493** [comment] 2021-05-04 05:41
page.chars is actually wrong. This of course leads to words being wrongly extracted. Here is the characters image. There seems to be a shift in character in y axis for some.

![asd_chars](https://user-images.githubusercontent.com/15212113/116964546-6baf8100-acc9-11eb-95c4-120a82df4273.png)

**Comment by jsvine** [comment] 2021-05-08 20:48
Hi @sreeni5493, `pdfplumber` depends on  `pdfminer.six` for coordinate extraction. Have you compared the coordinate output here to the [those in `pdfminer.six`](https://pdfminersix.readthedocs.io/en/latest/tutorial/extract_pages.html)? (For that, see `y0` and `y1` instead of `top`/`bottom`.) Are those also off? If so, better to file an issue there. Or does it appear that `pdfplumber` is introducing errors?

**Comment by samkit-jain** [comment] 2021-05-09 09:53
I missed the notification for this issue and was just reminded of it after the reply from @jsvine, @sreeni5493, In such cases, my first intuition is to try and repair the PDF using Ghostscript and when I did repair the PDF using it, the issue is no more. See the screenshots below for both the pages 1 and 2
![page1](https://user-images.githubusercontent.com/15127115/117567405-de5d9980-b0d9-11eb-8817-b41d400e56fc.png)
![page2](https://user-images.githubusercontent.com/15127115/117567438-00efb280-b0da-11eb-87a2-d689b05a2ccc.png)

Attaching the repaired PDF as well for your use. [repaired.pdf](https://github.com/jsvine/pdfplumber/files/6447262/repaired.pdf)

To repair the PDF on your own, you may use the following command
```sh
gs -o repaired.pdf -sDEVICE=pdfwrite input.pdf 
```

And yes, while I do understand that selectively running the command on certain PDFs may not fit well in your flow, I recommend you check Jeremy's reply and see if the issue stems for `pdfminer.six` instead.

**Comment by jsvine** [comment] 2021-05-09 20:58
Smart to test that, @samkit-jain. Many thanks. Closing this issue, given your findings.

**Closed as completed by jsvine** 2021-05-09 20:58 UTC

**Comment by sreeni5493** [comment] 2021-05-10 05:39
@jsvine @samkit-jain  Is it possible to do this repairing in pdfplumber without gs? gs is not commercial. Also since we deal with PDFs here there are chances of some cases where PDFs might be like this. Is it possible to have this repair functionality in pdfplumber? Also what was the issue that caused this? Any idea?

**Comment by sreeni5493** [comment] 2021-05-10 05:39
Also, big thanks to both of you.

**Comment by sreeni5493** [comment] 2021-05-10 07:49
Btw posted this issue in pdfminer.six. Is it active? The last issue they tried replying was back in March 12.

**Comment by samkit-jain** [comment] 2021-05-11 04:13
>Is it possible to do this repairing in pdfplumber without gs? Is it possible to have this repair functionality in pdfplumber?

Not sure but ideally, it should be present at the `pdminer.six` level and `pdfplumber` facilitating the fixing via that.

>gs is not commercial.

Ghostscript has licenses for both commercial and non-commercial usage as can be found at https://www.ghostscript.com/download/gsdnld.html.

>Also what was the issue that caused this? Any idea?

I haven't looked into this in much detail so can't comment as of now as any comment I make will just be an assumption.

**Comment by jsvine** [comment] 2021-05-11 13:25
Thanks @samkit-jain, and I agree: Repairing malformed PDFs is outside the scope of this library.

And @sreeni5493, passing `-dDEBUG` to the `gs` command may reveal some additional clues, although I'm not particularly familiar with that output.

**Comment by sreeni5493** [comment] 2021-06-02 11:33
It seems pdfminer is inactive for a long time. 

Issues are not getting any response from anyone relevant from the contributors or authors.

https://github.com/pdfminer/pdfminer.six/issues/619  (Issue related to this which I have posted there)

Similar issue just before mine:
https://github.com/pdfminer/pdfminer.six/issues/618

This Y-offset issue is something that is persistent in pdfminer. Not just the PDF issue I raised.

Is pdfminer being inactive going to be an issue for us on the longer run?

**Comment by jsvine** [comment] 2021-06-05 15:57
Hi @sreeni5493 — yes, it seems that the maintainers of `pdfminer.six` sometimes take a break, which to me seems natural and common for open-source projects. If it goes permanently inactive I may consider finding other backends to handle the PDF parsing; right now, though, it still seems like the best option and is heavily depended on by this project.
