### ISSUE TITLE
readpdf table result is None and text is None

### ISSUE THREAD

**Issue by laizezhong** [jsvine/pdfplumber#396] opened 2021-03-22 10:16 UTC
## MY python3.75 code：
`pdf = pdfplumber.open(r'abcd.pdf')
p0 = pdf.pages[0]
text = p0.extract_text()
print(text)
tables= p0.extract_tables()
print(tables)
`

the text result is None
the tables result is None
p0.objects.chars is []
why all the result is empty?  can anybody help me, thank you very much~

## PDF file
https://github.com/laizezhong/public/blob/2d350791f15f5b84601d4ca6612b304b910dc5a3/abcd.pdf

![1](https://user-images.githubusercontent.com/18032461/111974690-a6ef5980-8b3a-11eb-8fe9-bd2e3729da24.png)

**Comment by samkit-jain** [comment] 2021-03-22 10:32
Hi @laizezhong Thanks for raising this and providing the PDF. This issue seems to be a duplicate of #170, #332 and #335. Hence, I am closing this issue.

Request you to run pdfminer's `pdf2txt` as described in https://pdfminersix.readthedocs.io/en/latest/tutorial/commandline.html#pdf2txt-py and if no text is extracted, raise an issue over at https://github.com/pdfminer/pdfminer.six/issues. If it is recognised, then please reopen this issue.

**Closed as completed by samkit-jain** 2021-03-22 10:32 UTC
Labels: bug

**Comment by laizezhong** [comment] 2021-03-22 10:59
samkit-jain, Thank you ~
It work done when I upgraded the version of pdfplnumber from 0.5.24 to 0.5.27.
Thanks,
