### ISSUE TITLE
page.extract_table() result is None?

### ISSUE THREAD

**Issue by yts2020** [jsvine/pdfplumber#508] opened 2021-09-22 10:32 UTC
When I run page.extract_table(),the result is [[''], [''], [''], ['']]?
![Selection_100](https://user-images.githubusercontent.com/74759700/134328376-93c55b6d-800a-472e-8e80-e1466f557706.png)

**Comment by samkit-jain** [comment] 2021-09-22 13:20
Hi @yts2020 Appreciate your interest in the library. Could you please update the issue with the details as mentioned in https://github.com/jsvine/pdfplumber/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md?

**Comment by kt10001** [comment] 2021-11-01 16:09
Hi @samkit-jain  
my code on macos is ok, but on centos7 is None.

this is my pdf file.
[ali001.pdf](https://github.com/jsvine/pdfplumber/files/7454539/ali001.pdf)

pdfplumber==0.5.28

![image](https://user-images.githubusercontent.com/44205101/139702735-f77db8e5-b71a-4ffb-9639-218e74c9e209.png)

my code 
```
import pdfplumber
import re

path = '/tmp/ali001.pdf'
pdf = pdfplumber.open(path)

for page in pdf.pages[:2]:
    print(page.extract_text())
    for pdf_table in page.extract_tables():
        print(pdf_table)
        table = []
        cells = []
        for row in pdf_table:
            if not any(row):
                if any(cells):
                    table.append(cells)
                    cells = []
            elif all(row):
                if any(cells):
                    table.append(cells)
                    cells = []
                table.append(row)
            else:
                if len(cells) == 0:
                    cells = row
                else:
                    for i in range(len(row)):
                        if row[i] is not None:
                            cells[i] = row[i] if cells[i] is None else cells[i] + row[i]
        for row in table:
            print([re.sub('\s+', '', cell) if cell is not None else None for cell in row])
        print('---------- ----------')

pdf.close()
```

run result 
![image](https://user-images.githubusercontent.com/44205101/139703150-09a332ed-42a8-4864-9571-ac791acf74b5.png)

**Comment by kt10001** [comment] 2021-11-01 16:17
its pdf version or font ?

how i solve

**Comment by samkit-jain** [comment] 2021-11-01 17:14
@feikongl I too am unable to extract the text on my Ubuntu 18.04 machine. The PDF contains the font STSONG and I think it is a duplicate of https://github.com/jsvine/pdfplumber/issues/332. If you are able to run on MacOS, it could be that it contains the font and is able to map correctly. CentOS 7 may not have the font and is unable to map. I haven't tried but I found the following and it might be of help to you
1. https://programmerall.com/article/6175933567/
2. https://stackoverflow.com/questions/17435434/missing-chinese-characters-on-linux-running-birt-report

If you find any other solution that helped you install the font and resolve the issue, please share here.

**Closed as completed by samkit-jain** 2021-11-01 17:14 UTC
Labels: bug, awaiting-code-or-pdf

**Comment by kt10001** [comment] 2021-11-01 17:18
@samkit-jain  thank you.  i will try.
