### ISSUE TITLE
Memory Leakage

### ISSUE THREAD

**Issue by cabudies** [jsvine/pdfplumber#263] opened 2020-09-01 10:17 UTC
## Describe the bug

While opening and closing a pdf using 'with' parameter, pdfplumber somehow still takes up 120 mb space. Tried working using tempfile directory but still no success. Do anyone know how to deal with memory leakage issues?

## Code to reproduce the problem

with pdfplumber.open(pdf_filename) as pdf:

## Expected behavior

After the program gave results using the 'with' statement, the memory should reduce to 0 or 10 mb max.

## Actual behavior

It retained the value even I have tried memory_profiler to view it and used gc.collect() (garbage collector).

## Environment

- pdfplumber version: 0.5.23
- Python version: 3.6.6
- OS: Linux

**Comment by jsvine** [comment] 2020-09-01 11:38
Thank you for flagging this. Is this true of all PDFs you try opening, or one in particular?

**Comment by jsvine** [comment] 2020-09-02 02:56
I'm now able to reproduce this issue. Based on a bit of exploration, it seems that the memory issues might stem from within `pdfminer.six`, possibly in `PDFPageInterpreter.execute(...)` or `PDFContentParser`. Will continue looking into this.

**Comment by cabudies** [comment] 2020-09-18 06:57
> I'm now able to reproduce this issue. Based on a bit of exploration, it seems that the memory issues might stem from within `pdfminer.six`, possibly in `PDFPageInterpreter.execute(...)` or `PDFContentParser`. Will continue looking into this.

So sorry was not able to reply promptly. Yeah I have checked this is for all the pdfs is it possible that we can check or drop the pdfminer.six after our extraction is complete to free up used space.

**Comment by jsvine** [comment] 2022-07-20 20:01
Closing this issue as duplicate of #193

**Closed as completed by jsvine** 2022-07-20 20:01 UTC
Labels: bug
