### ISSUE TITLE
command not found issue

### ISSUE THREAD

**Issue by Arwa200** [jsvine/pdfplumber#272] opened 2020-09-14 09:30 UTC
Hi

I just tried the command line: 
curl "https://raw.githubusercontent.com/jsvine/pdfplumber/stable/examples/pdfs/background-checks.pdf" > background-checks.pdf
then: 
pdfplumber < background-checks.pdf > background-checks.csv

![Screen Shot 2020-09-14 at 11 59 19 AM](https://user-images.githubusercontent.com/42224049/93069196-0f3e1980-f686-11ea-972e-6339eb5d0f0a.png)
 but i got the "command not found: pdfplumber" while I already install the pdfplumber

please see the attachment..

**Comment by samkit-jain** [comment] 2020-09-14 09:41
Hi @Arwa200 Could you please share the output of `python -c "import pdfplumber"`?

---

On the contrary, it looks like you are using Python 2 without a virtual environment. Unless this is intentional, I would recommend you to switch to Python 3 (3.6+) and use a virtual environment.

**Comment by Arwa200** [comment] 2020-09-14 09:43
I'm using python 3 
![Screen Shot 2020-09-14 at 12 42 37 PM](https://user-images.githubusercontent.com/42224049/93070686-da32c680-f687-11ea-9f9c-215172502ffd.png)
I will try the  virtual environment.

**Comment by Arwa200** [comment] 2020-09-14 10:02
![Screen Shot 2020-09-14 at 1 01 23 PM](https://user-images.githubusercontent.com/42224049/93072708-73fb7300-f68a-11ea-8979-2f120adbfc46.png)

**Comment by samkit-jain** [comment] 2020-09-14 11:33
Would it be possible for you to share steps to reproduce this issue? Also the OS, Python version and library version

For me, the steps are
```sh
$ python3.8 -m venv venv  # create a py38 virtual environment by the name "venv"
$ source venv/bin/activate  # activate the virtual environment
(venv) $ pip install pdfplumber  # install the latest version of the library
(venv) $ curl "https://raw.githubusercontent.com/jsvine/pdfplumber/stable/examples/pdfs/background-checks.pdf" > background-checks.pdf && pdfplumber < background-checks.pdf > background-checks.csv  # run the command
```
and it works fine

**Comment by Arwa200** [comment] 2020-09-14 11:54
I still have the empty file..

![Screen Shot 2020-09-14 at 2 48 46 PM](https://user-images.githubusercontent.com/42224049/93082485-aeb8d780-f699-11ea-92b0-63aca2b5affb.png)

another question, where can I enter the keyword that I want to pull a whole raw information that has related to that row

thank you

**Comment by samkit-jain** [comment] 2020-09-14 12:19
Could you please run with `background-checks.pdf` and not `2020-shipping-section.pdf` because there is no such file at the path https://github.com/jsvine/pdfplumber/tree/stable/examples/pdfs?

>where can I enter the keyword that I want to pull a whole raw information that has related to that row

Could you please elaborate a more on this?

**Comment by Arwa200** [comment] 2020-09-14 12:29
sure
its worked
but the question is how to make it worked in my PDF?
I mean if I want to search for specific keyword in PDF file like "ABC" related to that word..?

**Comment by samkit-jain** [comment] 2020-09-14 12:49
Hi @Arwa200 Could your question be rephrased as "How do I get the coordinates of a particular word in a PDF?" If yes, you can use the `.extract_words()` function for that. If you could share the PDF and the expected output, that'd be helpful.

**Comment by Arwa200** [comment] 2020-09-14 12:54
Yes, this my question 
How do I get the coordinates of a particular word in a PDF and save it into CSV? 
I would rather not to share it since there are many, so would you please tell how to add the PDF files in the path and how to use .extract_words() in Command line 

appreciate your efforts..

**Comment by samkit-jain** [comment] 2020-09-14 15:09
@Arwa200 Try using the following
```python
import pdfplumber

pdf = pdfplumber.open("file.pdf")
p = pdf.pages[0]

for word_dict in p.extract_words():
    if word_dict["text"] == "WordToFind":
        print(word_dict)
        break
```

You can find the coordinates in `word_dict`. Replace `WordToFind` with the word you want to find.

**Comment by Arwa200** [comment] 2020-09-15 06:49
I got these errors, 
![Screen Shot 2020-09-15 at 9 48 43 AM](https://user-images.githubusercontent.com/42224049/93175678-afed1180-f738-11ea-9401-48b69eb6c926.png)

also How to save results in CSV in this case?

**Comment by Arwa200** [comment] 2020-09-15 06:53
I'm wondering where can I find the same code (in the up) in test folder or pdfplumber folder

**Comment by Arwa200** [comment] 2020-09-15 07:28
also I changed the URL, but still there is an error 
![Screen Shot 2020-09-15 at 10 27 01 AM](https://user-images.githubusercontent.com/42224049/93179278-1fb1cb00-f73e-11ea-8956-7c37e1ea02e7.png)

**Comment by samkit-jain** [comment] 2020-09-15 09:18
The error in https://github.com/jsvine/pdfplumber/issues/272#issuecomment-692504902 means you don't have `pdfminer` installed. Are you sure you have activated the correct virtual environment and running `pip install pdfplumber` didn't throw any error? Have you tried reinstalling `pdfplumber`? Have you tried running `pip install pdfminer.six` instead?

For https://github.com/jsvine/pdfplumber/issues/272#issuecomment-692523459, could you confirm if `python -c "import pdfplumber"` is running without any error?

**Comment by Arwa200** [comment] 2020-09-15 09:44
yes pdfplumber it's already there.. 
![Screen Shot 2020-09-15 at 12 42 44 PM](https://user-images.githubusercontent.com/42224049/93194684-06fee080-f751-11ea-8111-c1f9305a8841.png)

python -c "import pdfplumber": 
![Screen Shot 2020-09-15 at 12 43 01 PM](https://user-images.githubusercontent.com/42224049/93194685-06fee080-f751-11ea-9454-1cfa461251c2.png)

**Comment by samkit-jain** [comment] 2020-09-15 10:03
Could you please switch to Python 3.6 or higher? Looks like you are on 2.7 and if I am correct, the support for it was dropped in pdfplumber 0.5.15. The latest version is 0.5.23

**Comment by Arwa200** [comment] 2020-09-15 10:04
it's pyhton 3
![Screen Shot 2020-09-15 at 1 03 53 PM](https://user-images.githubusercontent.com/42224049/93197121-ef752700-f753-11ea-83f6-07d1f01b1819.png)

**Comment by samkit-jain** [comment] 2020-09-15 12:31
Okay. Request you to run the following steps in order and share the output of those.

1. Start a new terminal session.
2. Create a new folder. `mkdir test_folder`.
3. Switch to the new folder. `cd test_folder`.
4. Create a new Python 3.8 virtual environment by the name "venv". `python -m venv venv`. I am assuming `python` by default refers to Python 3.8 on your system. If not, replace `python` with the correct keyword.
5. Activate the virtual environment. `source venv/bin/activate`.
6. Verify Python installation. `python -V`.
6. Install pdfplumber. `python -m pip install pdfplumber --no-cache-dir`.
7. Verify pdfplumber installation. `python -c "import pdfplumber"`
8. Create a new Python file `main.py` and save the code in https://github.com/jsvine/pdfplumber/issues/272#issuecomment-692121431 in it (updating the file paths).
9. Run the script `python main.py`.

**Comment by Arwa200** [comment] 2020-09-16 08:13
Hi 

just tried what you write, I got this error in python3 
I do not know how to open the file 

![Screen Shot 2020-09-16 at 11 12 45 AM](https://user-images.githubusercontent.com/42224049/93310549-9a95e700-f80d-11ea-8d56-7953dae9c172.png)


![Screen Shot 2020-09-16 at 11 11 07 AM](https://user-images.githubusercontent.com/42224049/93310389-628ea400-f80d-11ea-8633-b2ee8d9200dc.png)

**Comment by samkit-jain** [comment] 2020-09-16 12:05
Thank you for trying out the steps @Arwa200 Did you follow step 9? If you did and created a file `main.py`, was it in the root folder `test_folder` or somewhere else? The reason the last step is failing because there is no file `main.py` in the folder `test_folder`.

Don't forget to update `file.pdf` with the correct PDF path.

**Comment by Arwa200** [comment] 2020-09-16 12:16
Thank you for being patient..
I tried it, and got this.. 

![Screen Shot 2020-09-16 at 3 16 17 PM](https://user-images.githubusercontent.com/42224049/93335771-9aa6de80-f82f-11ea-9b74-974885fd2934.png)

also I put the file.pdf at the same folder in main.py 

main.py is in the test_folder
![Screen Shot 2020-09-16 at 3 09 02 PM](https://user-images.githubusercontent.com/42224049/93335778-9d093880-f82f-11ea-9fef-c3a4d4553a4b.png)

![Screen Shot 2020-09-16 at 3 13 28 PM](https://user-images.githubusercontent.com/42224049/93335788-9e3a6580-f82f-11ea-8475-818030010cf7.png)

**Comment by samkit-jain** [comment] 2020-09-16 12:36
No problem @Arwa200 I am here to help only :)

Could you run `python main.py` again but this time use [background-checks.pdf](https://github.com/jsvine/pdfplumber/blob/stable/examples/pdfs/background-checks.pdf) and not your file (don't forget to update the path)? If it works and throws no error, there might be a problem with your PDF. It could be corrupted. Perhaps repairing it via Ghostscript would help. Can repair the PDF by running 
```
gs -o "output.pdf" -sDEVICE=pdfwrite input.pdf 
```
You would need to have Ghostscript installed. Without the PDF, there's not much I can do. Maybe you can redact sensitive information from the PDF and then share it?

**Comment by samkit-jain** [comment] 2020-09-16 12:39
Searching around for `PDFSyntaxError: No /Root object! - Is this really a PDF?`, it looks like a lot of people had this issue and were using Windows and were able to solve by opening the file in binary mode.

**Comment by samkit-jain** [comment] 2020-09-16 12:43
Found a similar issue on pdminer.six https://github.com/pdfminer/pdfminer.six/issues/476 and I repaired the PDF with ghostscript and it worked fine.

**Comment by Arwa200** [comment] 2020-09-16 12:50
The result after trying your PDF 

![Screen Shot 2020-09-16 at 3 48 43 PM](https://user-images.githubusercontent.com/42224049/93339460-494d1e00-f834-11ea-9663-d48c053296ad.png)

**Comment by samkit-jain** [comment] 2020-09-16 12:53
In below code, you have to replace `WordToFind` and not `text` with `Iowa`
```python
for word_dict in p.extract_words():
    if word_dict["text"] == "WordToFind":
        print(word_dict)
        break
```
It would become
```python
for word_dict in p.extract_words():
    if word_dict["text"] == "Iowa":
        print(word_dict)
        break
```
Also, the fact that the code ran so far confirms that the issue stems from the PDF. I would recommend you to give repairing it a shot. Should resolve your issue.

**Comment by Arwa200** [comment] 2020-09-16 13:05
it worked with your file :) for both functions (word_dict/WordToFind )

![Screen Shot 2020-09-16 at 4 05 26 PM](https://user-images.githubusercontent.com/42224049/93341215-7bf81600-f836-11ea-95c3-cab667fef222.png)

I will check the ghostscript you just mentioned.. 

But How can I save the result into csv? 


Thank you again!

**Comment by samkit-jain** [comment] 2020-09-16 13:17
For saving the data into a CSV file, you should look at the [csv module](https://docs.python.org/3/library/csv.html) in Python. A good tutorial can also be found [here](https://realpython.com/python-csv/).

I am closing this issue now. If repairing the PDF does not solve the issue (in which case opening an issue on [pdfminer.six GitHub](https://github.com/pdfminer/pdfminer.six/issues/new) would be more suited since `pdfplumber` uses it for parsing PDFs internally) or you need further assistance, feel free to reopen it.

**Closed as completed by samkit-jain** 2020-09-16 13:17 UTC
Labels: troubleshooting
