### ISSUE TITLE
Context manager doesn't close file on exceptions

### ISSUE THREAD

**Issue by augeos-grosso** [jsvine/pdfplumber#578] opened 2022-01-12 10:02 UTC
## ```pdfplumber.open()``` doesn't seem to be releasing the file when an error occurs in intself

I am trying to make my code robust to exceptions and good at logging them.
I needed some files to test exceptions with, so i created a new empty text document and renamed it to "empty.pdf".

My code's workflow is:
- scan a directory full of PDFs
- for each PDF:
    - ```pdfplember.open()``` it
    - extract text, tables, and whatever else
    - move the file to an "old" directory with ```os.rename```

## Code to reproduce the problem

to keep it simple I cut the input and output folders from the equations, as well as the loop on the input folder and the logging part

```
import pdfplumber
import os

try:
    with pdfplumber.open("empty.pdf") as pdf:
        pdf.do_something() # it won't even reach this point, you are good to copy and run the whole code
except Exception:
    # log the exception and keep the process going
    pass
os.rename("empty.pdf", "_empty.pdf")
```

## PDF file

Again:
just create an empty text document and rename it to "empty.pdf"

## Expected behavior

The file should be moved to the new location (in this simplified version, just renamed), even if an exception occurred

## Actual behavior

The program throws a ```PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'empty.pdf' -> '_empty.pdf'```
**BUT** if you open a "good" pdf, and then raise an exception inside the with-block, the program works as intended.

## Environment

- pdfplumber version: 0.6.0
- Python version: 3.10
- OS: Windows 10

## Additional context

If in the ```except:``` block I open another file (wheter an empty PDF or not), the ```rename``` part works flawlessly, and this is making me think that when you call ```pdfplumber.open()``` it "resets" all handlers it had before.
Unfortunately I didn't try with a corrupted PDF because i don't have one at this time, but my goal was to catch exception raised because of bad PDFs. I suppose the problem would be present even if you were to use a currupted PDF

**Comment by samkit-jain** [comment] 2022-01-12 17:33
Hi @augeos-grosso Appreciate your interest in the library and thanks for raising this. For me, with
* pdfplumber version: 0.6.0
* Python version: 3.8
* OS: Ubuntu 18.04

I am unable to reproduce the issue. However, I think it can be solved by adding a try-except block at https://github.com/jsvine/pdfplumber/blob/b904dd6a7c5164c5e051fa9b4121f8af6a105ae9/pdfplumber/pdf.py#L55 and closing the file on exception. @jsvine If you have access to a Windows machine, perhaps you can give it a shot. Or else, @augeos-grosso you can try as well and if it works, can raise a PR for it.

**Closed as completed** 2022-01-14 23:57 UTC
Labels: bug
