### ISSUE TITLE
STSong-light typeface not recognized

### ISSUE THREAD

**Issue by flyingpig-yf** [jsvine/pdfplumber#332] opened 2021-01-06 06:07 UTC
Hello，I am applying pdfplumber to parse the pdf with STSong-light typeface but I got all blanks
[‘ ‘，‘ ‘，‘ ‘，‘ ‘]
pdfminer.six cannot recognize the characters？Any solutions？
pdfminer.six 20200517
pdfplumber 0.5.25
Python37
Thanks.

## PDF file
[demo.pdf](https://github.com/jsvine/pdfplumber/files/5774123/demo.pdf)

## code
import pdfplumber
s = {"vertical_strategy": "lines", 
    "horizontal_strategy": "lines",
    "explicit_vertical_lines": [],
    "explicit_horizontal_lines": [],
    "snap_tolerance": 3,
    "join_tolerance": 3,
    "edge_min_length": 3,
    "min_words_vertical": 3,
    "min_words_horizontal": 1,
    "keep_blank_chars": True,
    "text_tolerance": 3,
    "text_x_tolerance": None,
    "text_y_tolerance": None,
    "intersection_tolerance": 3,
    "intersection_x_tolerance": None,
    "intersection_y_tolerance": None,}
file_path = "demo.pdf" 
pdf = pdfplumber.open(file_path)
p0 = pdf.pages[0]
print(p0.extract_table(table_settings=s))

**Comment by samkit-jain** [comment] 2021-01-06 09:18
Hi @flyingpig-yf Appreciate your interest in the library. I haven't looked into this deeply but my initial assessment would be that the issue is because the font is not embedded in the PDF. Here's a screenshot 
![image](https://user-images.githubusercontent.com/15127115/103750650-17eb9e80-502d-11eb-9f34-aa244ebb7e7f.png)
Whether pdfminer.six should be able to substitute the font, that I am not sure. Found a similar issue https://github.com/pdfminer/pdfminer.six/issues/482 there as well.

**Comment by jsvine** [comment] 2021-01-06 13:43
Thanks, @samkit-jain! And @flyingpig-yf, when you run `pdfminer.six`'s [`pdf2txt.py` tool](https://pdfminersix.readthedocs.io/en/latest/tutorial/commandline.html), does it recognize those characters?

**Comment by samkit-jain** [comment] 2021-01-06 13:56
Nope. Didn't recognise for me.

**Comment by jsvine** [comment] 2021-01-06 13:59
Thanks, @samkit-jain — I appreciate you looking into that. Closing this issue for now, as it appears to stem from `pdfminer.six`, rather than `pdfplumber`, and so is not easily addressed through this repository.

**Closed as completed by jsvine** 2021-01-06 13:59 UTC
Labels: troubleshooting

**Comment by samkit-jain** [comment] 2021-01-06 14:15
@flyingpig-yf I would suggest you raise an issue on the pdfminer.six' GitHub repo with the result of running `pdf2txt.py`.
