### ISSUE TITLE
The visualization result is right，but the extraction result is wrong！

### ISSUE THREAD

**Issue by OK-JH** [jsvine/pdfplumber#414] opened 2021-04-15 08:03 UTC
## Describe the bug

The visualization result is right，but the extraction result is wrong！and they use the same setting

## Code to reproduce the problem
the main codes as follow:
setting = {
            "vertical_strategy": "lines",
            "horizontal_strategy": "lines",
            "explicit_horizontal_lines": page.curves,
            "explicit_vertical_lines": page.edges+page.curves,
            # "snap_tolerance": 5,
            #"text_tolerance": 0.5,
            #"intersection_tolerance": 5,
            #"intersection_x_tolerance": 3,
            #"intersection_y_tolerance": 3
        }
im = page.to_image(resolution=150)
            im.reset().debug_tablefinder(setting)
            im.save('test.png', format='PNG')

## PDF file
[test.pdf](https://github.com/jsvine/pdfplumber/files/6316149/test.pdf)

## Screenshots
the visualization is next:
![image](https://user-images.githubusercontent.com/62200898/114833939-aa58c680-9e02-11eb-9b25-1708c343b97c.png)

the extraction result is next:
![image](https://user-images.githubusercontent.com/62200898/114833974-b3499800-9e02-11eb-9ec2-e5ac01b26194.png)

as you see, I do not konw why the numbers in yellow box are divided into the cell on the left.
I guess it is a bug.
looking forward to your reply!

## Environment

- pdfplumber version: 0.5.25
- Python version: 3.7
- OS: win 10

**Comment by samkit-jain** [comment] 2021-04-15 09:17
Hi @OK-JH Appreciate your interest in the library. If you draw the characters (`im.draw_rects(page.chars)`), you'll notice that those numbers are actually a part of the second column and not the third and that's why you are noticing this unexpected behaviour. ![image](https://user-images.githubusercontent.com/15127115/114844755-b770b800-9df8-11eb-831a-dc1549a2ed83.png)

As to why this is happening, I don't have an answer for that at the moment.

**Comment by jsvine** [comment] 2022-07-20 18:40
Thanks, @samkit-jain. Looks like the odd placement of those characters might be due to a font issue. [Repairing the PDF with ghostscript](https://superuser.com/a/282056) seems to fix that — re-locating the those numbers to their correct positions:

<img width="855" alt="Screen Shot 2022-07-20 at 2 36 52 PM" src="https://user-images.githubusercontent.com/534702/180057213-38dcb153-5e43-4f0d-9373-5fdbda6ede10.png">

... though creating some strange encoding issues in the table extraction:

```
[['项    目', None, '周期', '\x80术要求', '说明'],
 ['巡检 \n项目', '外Ê检查', '1o或必要时', '无异常', '参É6.1.2 aĀ'],
 [None, '油温和绕组温þ检查', '1o或必要时', '符合设备\x80术文件要求', '参É6.1.2 bĀ'],
 [None, '呼吸器检查', '1o或必要时', '~燥剂总量的1/3~~燥状态', '参É6.1.2 cĀ'],
 [None, '冷却系统检查', '1o或必要时', '无异常', '参É6.1.2 dĀ'],
 [None, 'p载V接开关检查', '1o或必要时', '无异常', '参É6.1.2 eĀ'],
 [None, '声响及振动检查', '1o或必要时', '无异常', '参É6.1.2 fĀ'],
 ['红外热像检测', None, '1o或必要时', '1o或必要时', '参É6.1.3'],
 ['本体油\x7f色谱V析',
  None,
  '3o或必要时',
  '乙炔f1ÿ\uf06dL/LĀÿ注意值Ā \n氢气f150ÿ\uf06dL/LĀÿ注意值Ā \n总烃f150ÿ\uf06dL/LĀÿ注意值Ā',
  '参É6.1.4'],
 ['直流偏磁电流检查', None, '必要时', '', '参É6.1.5']]
```

Given that this seems to be an issue with the PDF itself (or possibly the font-handling in `pdfminer.six`), rather than `pdfplumber`, I'm closing this issue. Feel free to continue the discussion, however.

**Closed as completed by jsvine** 2022-07-20 18:40 UTC
Labels: bug
